# Generated by Django 3.2.2 on 2021-05-06 11:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task', '0002_alter_task_assignee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Group', '0002_alter_group_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grpc', to='Group.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='usr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTaskConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grp', to='Group.group')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tsk', to='Task.task')),
            ],
        ),
    ]
