# Generated by Django 3.2.2 on 2021-05-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_auto_20210506_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
